---
title: " "
pagetitle: "David Ryan Miller"
output:
  html_document:
    includes:
      in_header: GA_Script.html
---

&nbsp;  

### *All the President's Organized Interests*

My book project, "All the President's Organized Interests," examines how presidents interact with organized interests to pursue their goals.  Though both scholars and practitioners acknowledge presidents and organized interests as formidable actors in American politics, few studies examine the interactions between these actors.  I posit that presidents engage with organized interests to channel their institutional resources, such as their electoral and lobbying capabilities, in service of presidents' goals.  I further argue that, in order to maximize the effectiveness of this engagement, presidents are more likely to engage with organized interests who have large resource endowments and who share the partisan and ideological preferences of the incumbent.  I assess these expectations by evaluating three interrelated questions: with which organized interests do presidents engage?; how do presidents encourage the interests with which they engage to cooperate with them?; and how does presidents' engagement with organized interests help presidents achieve their goals?

My theory and empirical expectations rest on the assertion that presidents, not organized interests, exert primary control over engagement, or reciprocal communication and coordination between presidents and organized interests concerning electoral or policy goals.  Because this assertion diverges from the traditional understanding of organized interests' interactions with policymakers, wherein interests' motives and strategic choices drive engagement, I draw on 15 interviews with former White House officials and organized interest representatives and a survey conducted with over 700 federal lobbyists to demonstrate how presidents take the lead in engaging with interests.  Evidence drawn from these interviews and survey responses indicate that organized interests tend to focus their lobbying efforts on Congress and the bureaucracy, such that interactions with the White House are more likely to be driven by the president; that the White House actively cultivates relationships with interests and initiates instances of engagement; and that organized interests are more responsive to entreaties from the White House than vice versa.  Collectively, this evidence illustrates that, unlike in other institutional venues, presidents' motives and strategic choices guide their decisions to engage with organized interests.

After establishing the primacy of presidents in the engagement dynamic and explicating my theory, I turn to evaluating my three research questions.  First, I consider with which organized interests presidents engage.  I argue that presidents engage with interests from whom they expect the highest rates of return from engagement: interests with large resource endowments and who share the incumbent's ideological and partisan preferences.  To test these expectations, I utilize over 7 million White House visitor logs records from the Clinton and Obama presidencies to identify instances in which presidents provided access to organized interests.  I further supplement these records with other data sources, including Lobbying Disclosure Act filings and White House personnel salary reports.  While some of this data is accessible online, I acquired much of it through FOIA requests and archival work at the Clinton Presidential Library.  I leverage this data to estimate multilevel models examining the relationships between organized interests' White House access and their lobbying expenditures, campaign contributions to candidates for federal office, and the partisan alignment of their industries with the incumbent.  I find that presidents are more likely to provide access to interests with higher levels of resources and to interests in industries aligned with the incumbent's party, suggesting that presidents perpetuate inequalities in political voice present in other institutions.

Second, I examine how presidents encourage cooperation from organized interests.  Though interests sometimes cooperate with presidents because of shared goals, presidents can incentivize recalcitrant interests or boost the effort interests exert with selective incentives at their disposal by way of their unilateral powers.  I argue that presidents allocate these incentives to organized interests to whom they provide White House access.  I evaluate this expectation with multilevel models which assess whether presidents are more likely to provide federal grants, appointments to advisory commissions, and mentions in the White House's public statements to organized interests to whom they previously provided access.  My results support this expectation, suggesting that presidents'  engagement with organized interests contributes to disparities not only in political voice, but also the distribution of political and policy resources.

Third, I examine whether presidents' engagement with organized interests advances their goals.  In many cases, organized interests' activity with regard to presidents' initiatives is hard to observe.  For example, lacking information about when presidents encourage interests to pressure Congress on their behalf and records of interests' efforts to lobby members of Congress, we cannot evaluate whether presidential engagement induces organized interests to exert lobbying effort and whether that effort advances' presidents objectives.  In light of this challenge, I use an experimental approach to recreate this typically unobservable strategic environment.  Specifically, I evaluate whether presidential engagement efforts motivate organized interests to utilize institutional resources in ways consonant with the White House's preferences through a survey experiment conducted with nearly 900 federal lobbyists.  Subsequently, I examine whether organized interests' public statements of support for presidents' priorities\textemdash one of the key activities the White House encourages interests to conduct\textemdash increases public support for those priorities.  My results indicate that presidential engagement increases organized interests' willingness to exert effort on behalf of presidents' priorities and that interests' statements of support for presidents' priorities bolster public approval for those policies.

My book project both offers theoretical contributions to several different areas of study in American politics and highlights substantive implications of presidents' interactions with organized interests.  I not only help to start bridging the scholarly gap between the presidency and organized interests, but also demonstrate how presidents use their powers to provide representation to select subgroups of the political system, rather than the country as a whole, in a context outside of electoral politics.  Further, whereas recent research on the presidential toolkit focuses on formal powers presidents can exercise unilaterally, such as executive orders and the management of appointments and vacancies in the bureaucracy, I highlight an overlooked utensil in the toolkit: presidents' ability to mobilize coalitions of organized interests.  In addition, whereas most studies of organized interests' influence on the policy process focus on Congress, I highlight the pathways by which organized interests enjoy influence through the executive branch and consider how the president perpetuates inequality of political voice among the universe of interests in society.

This book project emerges from my dissertation, which received the 2021 George C. Edwards III Dissertation Award from APSA's Presidents and Executive Politics section.