---
title: " "
pagetitle: "David Ryan Miller"
output:
  html_document:
    includes:
      in_header: GA_Script.html
---

&nbsp;  

### Journal Articles

[Butler, Daniel M. and David R. Miller.  "Does Lobbying Affect Bill Advancement?  Evidence from Three State Legislatures." *Forthcoming at Political Research Quarterly*.](files/LobbyingImpact.pdf)

- [Supplemental Information](files/LobbyingImpactSI.pdf)

[Miller, David R. "The President Will See Whom Now?  Presidential Engagement with Organized Interests." *Conditionally accepted at American Political Science Review*.](files/APSR_Final_Main.pdf)

- [Supplemental Information](files/APSR_Final_SI.pdf)

[Ladam, Christina, Austin Bussing, Alexander C. Furnas, Josh McCrain, David R. Miller, and Rachel Porter.  2022.  "The Junior Americanist Workshop Series (JAWS)."  *PS: Political Science & Politics*, 55(3):552-553.](files/JAWS PS Submission.pdf)

[Miller, David R.  2022.  "On Whose Door to Knock? Lobbyists' Strategic Pursuit of Access to Members of Congress."  *Legislative Studies Quarterly*, 47(1), 157-192.](files/DRM_Targeting_final.pdf)

[Miller, David R. and Andrew Reeves.  2022.  "Pass the Buck or the Buck Stops Here?  The Effectiveness of Claiming and Deflecting Blame by Elected Executives."  *Journal of Public Policy*, 42(1), 63-91.](files/main-rr.pdf)

[Miller, David R.  2021  "Empirical Approaches to the Study of Access." *Interest Groups \& Advocacy*, 10(3), 286-302.](files/AccessApproaches.pdf)

[Stein, Robert M., Christopher Mann, Charles Stewart III, $\ldots$, David Miller, $\ldots$, et al. 2020. "Waiting to Vote in the 2016 Presidential Election: Evidence from a Multi-county Study." *Political Research Quarterly*, 73(2), 439-453.](files/PRQ_Voting.pdf)

[Mann, Christopher B., Gayle A. Alberda, Nathaniel A. Birkhead, $\ldots$, David Miller, $\ldots$, et al. 2018. "Pedagogical Value of Polling Place Observation By Students." *PS: Political Science & Politics*, 51(4), 831-837.](files/Perspectives_Voting.pdf)

[Miller, David R. and Andrew Reeves. 2017.  "Attitudes toward Delegation to Presidential Commissions." *Presidential Studies Quarterly*, 47(3), 495-516.](files/Commissions.pdf) 

- [Supplemental Information](files/CommissionsAppendix.docx)

### Other Academic Publications

Stein, Robert M., Christopher Mann, Charles Stewart III, $\ldots$, David Miller, $\ldots$, et al. 2020. "Polling Place Quality and Access." In *The Future of Election Administration*, Mitchell Brown, Kathleen Hale, and Bridgett A. King, Eds.  Palgrave Macmillan, 83-100.

[Reeves, Andrew, David R. Miller, and Bryant Moy.  2018.  "U.S. Presidential Campaigns and Their Impact."  In *Oxford Bibliographies in Political Science*.](http://www.oxfordbibliographies.com/view/document/obo-9780199756223/obo-9780199756223-0156.xml)

### Working Papers

[Boston, Joshua, Benjamin Kassow, Ali Masood, and David R. Miller. "Save These Honorable Courts: The Consequences of Judicial Scandal on Specific and Diffuse Support."  *Invited to revise and resubmit at PS: Political Science & Politics*.](files/JudicialScandal.docx)

- [Supplemental Information](files/JudicialScandal_SI.pdf)

[Egerod, Benjamin C.K., Hans J.G. Hassell, Josh McCrain, and David R. Miller. "Hiring Faithful Agents, Expertise, or Connections? A Conjoint Survey Experiment on Lobbyist Hiring Decisions."](files/Lobbying_Hiring.pdf)

[Lewis, David E. and David R. Miller.  "Partisanship and Support for the Administrative State in the U.S. Senate."](files/LSQShort_Blind_Main.docx) 

- [Supplemental Information](files/LSQShort_Blind_SI.docx)

[Miller, David R. and Jeffrey Ziegler.  "Preferential Abstention in Conjoint Experiments."](files/preferential_abstention.pdf)

### Works in Progress

Miller, David R. and Chris Piper.  "Costs for Not Appointing?: The Public Attitudes Towards Executive Branch Vacancies."

### Public Scholarship

["Biden’s Supreme Court commission probably won’t sway public opinion" (with Andrew Reeves).  *The Conversation*.  June 16, 2021](https://theconversation.com/bidens-supreme-court-commission-probably-wont-sway-public-opinion-159658)

["New evidence that lobbying affects legislative outcomes."  *3Streams*.  May 30, 2021](https://medium.com/3streams/new-evidence-that-lobbying-affects-legislative-outcomes-c350b5ea5475)

["Here's the evidence lobbyists are trying to persuade your member of Congress."  *3Streams*.  February 2, 2021](https://medium.com/3streams/who-do-lobbyists-lobby-in-congress-af0d53315ee8)

["If Trump Took Responsibility for Coronavirus Missteps, It Might Actually Help Him" (with Andrew Reeves).  *The Washington Post*.  March 26, 2020.](https://www.washingtonpost.com/politics/2020/03/26/if-trump-took-responsibility-coronavirus-missteps-it-might-actually-help-him)

["Late to the Party (Nomination): How Primary Election Timing Disadvantages Missouri Voters."  In APSA's *RAISE the Vote Campaign*.  January 17, 2020.](https://connect.apsanet.org/raisethevote/2020/01/17/late-to-the-party-nomination-how-primary-election-timing-disadvantages-missouri-voters/)