---
title: " "
pagetitle: "David Ryan Miller"
output:
  html_document:
    includes:
      in_header: GA_Script.html
---

&nbsp;  

### University of California, Riverside

#### Instructor of Record

- Presidential Politics, Fall 2023 ([Most Recent Syllabus](files/POSC 100 Presidential Politics Syllabus.pdf); Course Evaluations for [Fall 2023](files/POSC100Fall23Evals.pdf))

### East Tennessee State University

#### Instructor of Record

- Advanced Research Methods (Independent Study), Spring 2023
- Interest Groups in American Politics, Fall 2022 ([Most Recent Syllabus](https://www.dropbox.com/scl/fi/pr5a4e4kpclyxxu1thscb/InterestGroups-Fall-2022.gdoc?dl=0&rlkey=kg1gw76tqmi5vw2vt10dwaqbe); Course Evaluations for [Fall 2022](files/PSCI3050--Interest Groups--Fall 2022.pdf))
- Introduction to American Government, Fall 2021, Spring 2022, Fall 2022, Spring 2023 ([Most Recent Syllabus](https://www.dropbox.com/scl/fi/064iw7ewinuwbvw7ran2g/IntroAmericanSyllabus--Spring2023.gdoc?dl=0&rlkey=mhl0qwyftpc23jeyxpxxnua99); Course Evaluations for [Fall 2021](files/PSCI1120--Intro American--Fall 2021.pdf), [Spring 2022](files/PSCI1120--Intro American--Spring 2022.pdf), [Fall 2022](files/PSCI1120--Intro American--Fall 2022.pdf), [Spring 2023](files/PSCI1120--Intro American--Spring 2023.pdf))
- Research Methods, Fall 2021, Spring 2022, Fall 2022, Spring 2023 ([Most Recent Syllabus](https://www.dropbox.com/scl/fi/kgdzckbxhmkl6az5rem7u/ResearchMethodsSyllabus--Spring2023.gdoc?dl=0&rlkey=jmriksvgwpz8jpsawpulre8jz); Course Evaluations for [Fall 2021](files/PSCI3440--Research Methods--Fall 2021.pdf), [Spring 2022](files/PSCI3440--Research Methods--Spring 2022.pdf), [Fall 2022](files/PSCI3440--Research Methods--Fall 2022.pdf), [Spring 2023](files/PSCI3440--Research Methods--Spring 2023.pdf))
- State and Local Government, Spring 2022 ([Most Recent Syllabus](https://www.dropbox.com/scl/fi/1gbmg9k2fcbq4iz9ixd2i/StateLocalSyllabus-Spring2022.gdoc?dl=0&rlkey=x6srx0h73fzgb9icmj2w4dz9f); Course Evaluations for [Spring 2022](files/PSCI3710--State and Local Govt--Spring 2022.pdf))

### Washington University in St. Louis

#### Instructor of Record

- Introduction to American Politics, Summer 2018 ([Syllabus](https://docs.google.com/document/d/1nIefZRRGtpqLM3sBiq17lF_inTiOXEOsMabpUvZ_5oE/edit?usp=sharing), [Course Evaluations](files/Intro-to-American-Summer-2018.pdf))

#### Teaching Assistant

- Introduction to American Politics, Fall 2016 & Fall 2017 (Instructor: Andrew Reeves) (Course Evaluations, [Fall 2016](files/Intro-to-American-Fall-2016.pdf) and [Fall 2017](files/Intro-to-American-Fall-2017.pdf))
- Public Policy Analysis: Assessment and Practical Wisdom, Spring 2017 (Instructor: Dan Butler) & Spring 2018 (Instructor: Keith Schnakenberg) (Course Evaluations, [Spring 2017](files/Public-Policy-Spring-2017.pdf) and [Spring 2018](files/Public-Policy-Spring-2018.pdf))
- Research Design and Methods, Spring 2019 (Instructor: Matt Gabel) ([Course Evaluations](files/RDM-Spring-2019.pdf))
- Quantitative Political Methodology (Undergraduate), Fall 2018 (Instructor: Betsy Sinclair) ([Course Evaluations](files/QPM-Fall-2018.pdf))

### University of Rhode Island

#### Teaching Assistant

- Introduction to American Politics, Fall 2013 & Fall 2014 (Instructor: Maureen Moakley) (Course Evaluations, [Fall 2014](files/PSC113-Fall-2014.pdf); 2013 is unavailable)
- Introduction to International Politics, Spring 2014 & Spring 2015 (Instructor: Marc Hutchison) (Course Evaluations, [Spring 2014](files/PSC116-Spring-2014.pdf) and [Spring 2015](files/PSC116-Spring-2015.pdf))

### Teaching Demonstration

[Click here](https://www.youtube.com/watch?v=xL6DUg7cTC0&t=2s) to watch an 18-minute short workshop on multilevel models I led for graduate students at Washington University in St. Louis in February 2020.  Materials to follow along can be found [here](files/TeachingDemoFiles.zip).